language: php
php:
  - 5.4

before_script:
  - pear channel-discover pear.phpunit.de
  - pear install pear/PHP_CodeSniffer >/dev/null
  - sudo apt-get install -qq links
  - phpenv rehash

script:
  - phpunit --coverage-text --coverage-html=report/ tests/ || echo
  - phpcs --standard=zend --report-width=100 *.php | grep -Ev "underscore|brace|parenthesis|Spaces|Line exceeds"
  - links -width 200 -dump report/DBo.php.html | perl -pe 'undef $/; s/<.*Legend//s' | grep -v "100.00%"

notifications:
  email:
    - thbley@gmail.com