language: php
php:
  - 5.4

before_script:
  - pear channel-discover pear.phpunit.de
  - pear install pear/PHP_CodeSniffer >/dev/null
  - sudo apt-get install -qq links
  - phpenv rehash

script:
  - phpunit --coverage-text --coverage-html=report/ tests/
  - phpcs --standard=zend --report-width=100 *.php | grep -Ev "\| (Spaces|Line exceeds|Opening brace|Opening parenthesis|Closing parenthesis)|valid camel"
  - sed -i 's/"danger">/"danger">+ /g' report/DBo.php.html
  - cat report/DBo.php.html
  - links -width 180 -dump report/DBo.php.html

notifications:
  email:
    - thbley@gmail.com
