language: php
php:
  - 5.4

before_script:
  - pear channel-discover pear.phpunit.de
  - pear install pear/PHP_CodeSniffer >/dev/null
  - pear install pear.phpunit.de/phploc >/dev/null
  - sudo apt-get install -qq links
  - phpenv rehash

script:
  - phpunit --coverage-text --coverage-html=report/ tests/ || echo
  - phpcs --standard=zend --report-width=100 *.php | grep -Ev "underscore|brace|parenthesis|Spaces|camel caps|Line exceeds|\-+"
  - links -width 200 -dump report/DBo.php.html | perl -pe 'undef $/; s/<.*Legend//s' | grep -v "100.00%"
  - phploc . | grep -Ev " 0$| 0 "
  - echo -n "Open TODOs " && grep -rn "TODO " *.php |  wc -l
  - echo -n "Open TODO2s " && grep -rn "TODO2 " *.php | wc -l

notifications:
  email:
    - thbley@gmail.com